### ISSUE TITLE
GitHub inverted icon not copy and pasting properly

### ISSUE THREAD

**Issue by kkbrooks** [kaleidocode-app/vscode-figma-icons#1]
When trying to copy and paste the "github inverted" icon, it says the icon has been copied to my clipboard, but when I go to paste it into a textbox with the codicons icon font applied it won't paste. Other icons like "github" work fine in the same textbox.

**Comment by miguelsolorio** [comment]
@kawilkin you might try re-installing the latest [codicons](https://github.com/microsoft/vscode-codicons/blob/master/dist/codicon.ttf) font file and then clearing your cache and restarting Figma. I'm seeing this working right now.

To clear your cache, enter this into your terminal:
```shell
sudo atsutil databases -remove && atsutil server -shutdown && atsutil server -ping
```

![image](https://user-images.githubusercontent.com/35271042/83809238-f7103480-a66a-11ea-9164-da7df1e2b675.png)

**Comment by kkbrooks** [comment]
@misolori I tried all that and it still doesn't seem to be working :/ When I have it set to "Create new text object" it just does this:
<img width="766" alt="Screen Shot 2020-06-04 at 5 14 14 PM" src="https://user-images.githubusercontent.com/47866467/83810873-d81f9b80-a686-11ea-82f3-f1f09736df54.png">

I redownloaded the font and reinstalled it using the new download. I also cleared the cache twice and restarted my whole machine too.

**Comment by miguelsolorio** [comment]
This was an issue with the Figma shared font that was outdated vs the updated version locally, so the icon didn't exist. Updated shared font and now it works.
